name: "[Ruby] Build & Test"

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/ruby_build_test.yml"
      - "ruby/optify-from_hash/**"
      - "tests/**"
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths:
      - ".github/workflows/ruby_build_test.yml"
      - "ruby/optify-from_hash/**"
      - "tests/**"

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  setup:
    # Drafts: Only run on Ubuntu.
    # Non-drafts: Run on both Ubuntu and macOS.
    name: "Setup Build Matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
    steps:
      - id: setup
        run: |
          if [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
            matrix='["ubuntu-latest"]'
          else
            matrix='["ubuntu-latest", "macos-latest"]'
          fi
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  test:
    name: "Build & Test"
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v4

    # Rust
    # Required for the main Ruby gem.
    # We will soon make a new version of the main Ruby gem that doesn't require Rust.
    - name: "[Rust] Setup cache"
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          ruby/optify
          rust/optify
        cache-on-failure: true
        shared-key: ${{ matrix.os }}-rust
    - name: "[Rust] Build"
      run: cargo build --release
      working-directory: ./rust/optify

    # Ruby
    # Gem: optify-from_hash

    # setup-ruby also runs `bundle install`.
    # It uses the Ruby version from .ruby-version.
    - uses: ruby/setup-ruby@v1
      name: "Setup"
      with:
        bundler-cache: true
        working-directory: ./ruby/optify-from_hash
    - name: "[from_hash] Lint"
      shell: bash
      run: |
        set -ex

        bundle exec tapioca gem --verify

        bundle exec srb tc
        bundle exec rubocop

        # Ensure that the RBS file is up-to-date.
        mkdir -p tmp
        bundle exec rbs prototype rbi rbi/optify_from_hash.rbi > tmp/optify_from_hash.rbs~
        diff -u sig/optify_from_hash.rbs tmp/optify_from_hash.rbs~
      working-directory: ./ruby/optify-from_hash
    - name: "[from_hash] Test"
      run: bundle exec rake test
      working-directory: ./ruby/optify-from_hash

    - name: "[from_hash] Build"
      if: github.ref != 'refs/heads/main' && matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        set -ex
        bundle exec rake build
      working-directory: ./ruby/optify-from_hash
      env:
        GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_API_KEY }}'

    - name: "[from_hash] Publish"
      if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
      # It probably just fails if the gem is already published.
      continue-on-error: true
      shell: bash
      run: |
        set -ex
        bundle exec rake release
      working-directory: ./ruby/optify-from_hash
      env:
        GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_API_KEY }}'

    # Gem: optify
    - name: "Check Ruby version"
      shell: bash
      run: |
        set -ex
        # The Ruby versions must be the same for both gems.
        diff -u .ruby-version ../optify/.ruby-version
      working-directory: ./ruby/optify-from_hash
    
    - name: "[optify] Install dependencies"
      shell: bash
      run: bundle install
      working-directory: ./ruby/optify
    - name: "[optify] Lint"
      shell: bash
      run: |
        set -ex

        bundle exec tapioca gem --verify

        bundle exec srb tc
        bundle exec rubocop

        # Ensure that the RBS file is up-to-date.
        mkdir -p tmp
        bundle exec rbs prototype rbi rbi/optify.rbi > tmp/optify.rbs~
        diff -u sig/optify.rbs tmp/optify.rbs~
      working-directory: ./ruby/optify
    - name: "[optify][Rust] Lint"
      run : cargo fmt -- --check
      working-directory: ./ruby/optify
    - name: "[optify][Rust] Clippy"
      run: cargo clippy --release --no-deps -- -D warnings --no-deps
      working-directory: ./ruby/optify
    - name: "[optify] Test"
      run: bundle exec rake test
      working-directory: ./ruby/optify